name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test on Multiple OS
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -U test_user -d test_db; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run tests
        env:
          DB_NAME: test_db
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_HOST: localhost
          DB_PORT: 5432
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python manage.py test

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ghactions
          chmod 600 ~/.ssh/ghactions
          # Очистка устаревших ключей
          ssh-keygen -R ${{ secrets.HOST }} || true
          # Добавление ключа сервера
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts || true

      - name: Deploy application
        run: |
          ssh -v -i ~/.ssh/ghactions ${{ secrets.DEPLOY_USER }}@${{ secrets.HOST }} << EOF
          set -e
          echo "Starting connection..."
          mkdir -p ${{ secrets.DEPLOY_PATH }}
          sudo chown ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_USER }} ${{ secrets.DEPLOY_PATH }}
          cd ${{ secrets.DEPLOY_PATH }}
          if [ ! -d ".git" ]; then
            echo "Initializing new Git repository for ${{ secrets.REPOSITORY_URL }}"
            git init
            git remote add origin ${{ secrets.REPOSITORY_URL }}
            git pull origin main
          else
            echo "Git repository ${{ secrets.REPOSITORY_URL }} found, pulling latest changes..."
            git pull origin main
          fi
          DB_USER=${{ secrets.DB_USER }} \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          DB_NAME=${{ secrets.DB_NAME }} \
          docker compose down
          DB_USER=${{ secrets.DB_USER }} \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          DB_NAME=${{ secrets.DB_NAME }} \
          docker compose up -d --build
          echo "Finishing connection..."
          sleep 10
          exit
          EOF
