name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ghactions
          chmod 600 ~/.ssh/ghactions
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts || true

      - name: Deploy application
        run: |
          ssh -v -i ~/.ssh/ghactions ${{ secrets.DEPLOY_USER }}@${{ secrets.HOST }} << EOF
          set -e
          mkdir -p ${{ secrets.DEPLOY_PATH }}
          cd ${{ secrets.DEPLOY_PATH }}
          # Проверка наличия .git директории
          if [ ! -d ".git" ]; then
            echo "Initializing new Git repository..."
            git init
            git remote add origin <your-repository-url>
            git pull origin main
          else
            echo "Git repository found, pulling latest changes..."
            git pull origin main
          fi
          docker-compose down || true
          docker-compose up -d --build
          EOF
